WRAP_CLASS("itk::InterpolateImageFunction" POINTER)
  UNIQUE(types "${WRAP_ITK_SCALAR};UC")
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${types})
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_D}" "${ITKT_I${t}${d}},${ITKT_D}")
      WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_F}" "${ITKT_I${t}${d}},${ITKT_F}")
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
